title: Aquarium by Aquarist Labs

description: >

  Experimenting on captive cephalopods since 2021

markdown: kramdown
theme: minima

# set to true to show excerpts on the homepage
show_excerpts: false

minima:
  date_format: "%Y-%m-%d %H:%M"

  # generate social links in footer
  social_links:
    github: aquarist-labs
    # twitter:

header_pages:
  - about.md
  - FAQ.md
  - LICENSE.md

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile

collections:
  minutes:
    output: true
